services:
  postgresql:
    image: postgres:17
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs-boilerplate
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
